name = "joro-app"
main = "api/worker.js"
compatibility_date = "2025-08-20"

[vars]
PRINTFUL_API_KEY = ""  # This will be set in the Cloudflare dashboard

[[routes]]
pattern = "/api/*"
script = "api/worker.js"
